CREATE TABLE Users(SSN INT PRIMARY KEY NOT NULL, UserType varchar(30), Password char(60), Address char(60), Phoneno BIGINT, Fname char(20), Mname char(20), Lname char(60), Username char(30));
INSERT INTO Users VALUES(192919291,'Technician','pass123','3000 Synergy park blvd',1010101010,'Donald','Jaya','Gupta','jayamdonal123');
INSERT INTO Users VALUES(14111291,'Traffic_Controller','pass123','750 Synergy park blvd',4311122020,'Raul','','Timmons','RaulTimxx');
INSERT INTO Users VALUES(122121710,'Admin','pass123','800 Synergy park blvd',6444506937,'Kristine','','Hanson','Khanson22');
INSERT INTO Users VALUES(205730332,'Technician','pass123','850 Synergy park blvd',5472330782,'Rodrigo','','Peralta','PeralRod');
INSERT INTO Users VALUES(576435630,'Admin','pass123','900 Synergy park blvd',5856355487,'Juwan','Funk','Lira','Lirafunk99');
CREATE TABLE Admins(A_Ssn INT PRIMARY KEY NOT NULL, FOREIGN KEY (A_Ssn) REFERENCES Users(SSN));
INSERT INTO Admins VALUES(192919291);
INSERT INTO Admins VALUES(576435630);
CREATE TABLE Staff (Mem_Union_number INT PRIMARY KEY NOT NULL, U_Ssn INT, Type char(20), Union_Name char(20), FOREIGN KEY (U_Ssn) REFERENCES Users(SSN));
INSERT INTO Staff VALUES(132455,12345, 'AIRM');
CREATE TABLE Flight(Flight_id INT PRIMARY KEY NOT NULL, CompanyName char(20), Weight FLOAT, Capacity INT);
INSERT INTO Flight VALUES(3214, 'United_Airlines', 1000, 200);
INSERT INTO Flight VALUES(3215, 'Qatar', 1000, 200);
INSERT INTO Flight VALUES(3216, 'Indigo', 1000, 200);
CREATE TABLE Announcement(Announcement_id INT PRIMARY KEY NOT NULL, Type char(20), Announcement_Time time, Notification varchar(1000));
INSERT INTO Announcement VALUES(1,'Pre Boarding','10:00:00','Good afternoon passengers. This is the pre-boarding announcement for flight 89B to Rome. We are now inviting those passengers with small children, and any passengers requiring special assistance, to begin boarding at this time. Please have your boarding pass and identification ready. Regular boarding will begin in approximately ten minutes time. Thank you.');
INSERT INTO Announcement VALUES(2,'Final Boarding','10:10:00','This is the final boarding call for passengers Erin and Fred Collins booked on flight 372A to Kansas City. Please proceed to gate 3 immediately. The final checks are being completed and the captain will order for the doors of the aircraft to close in approximately five minutes time. I repeat. This is the final boarding call for Erin and Fred Collins. Thank you.');
INSERT INTO Announcement VALUES(3,'Change-of-gate','12:00:10','Attention passengers on English Air flight 232 to Boise. The departure gate has been changed. The flight will now be leaving from Gate 26.');
INSERT INTO Announcement VALUES(4,'Flight-delay','10:10:41','This is an announcement for passengers on flight 232 to Boise. The flight has been delayed due to bad weather conditions. The flight crew has arrived at the gate, but the ground crew is still de-icing the wings of the aircraft. Our new departure time is 10:50 AM.');
INSERT INTO Announcement VALUES(5,'Overbook','14:21:12','I’m afraid that flight 232 is overbooked. We’re looking for passengers who are willing to take a later flight in exchange for a travel voucher worth $300. Any passenger who is interested should see an agent at Gate 26.');
CREATE TABLE Airport(Airport_id INT PRIMARY KEY NOT NULL, Type varchar(100), Address varchar(1000), Airport_Name varchar(1000));
INSERT INTO Airport VALUES(10,'Domestic','Tanbar QLD 4481, Australia','Arrabury Airport');
INSERT INTO Airport VALUES(11,'International','Abu Dhabi - United Arab Emirates','Al Ain International Airport');
CREATE TABLE Traffic_Controller(TC_id INT PRIMARY KEY NOT NULL, TC_Union_id INT, TC_Airport_id INT, Address varchar(100), Phone_no INT, Salary INT, FOREIGN KEY (TC_Union_id) REFERENCES Staff(Mem_Union_number), FOREIGN KEY (TC_Airport_id) REFERENCES Airport(Airport_id));
INSERT INTO Traffic_Controller VALUES(321, 44113, 12, 'Dallas Fort Worth', 9790445763, 100000);
INSERT INTO Traffic_Controller VALUES(323, 44114, 12, 'Dallas Fort Worth 2', 9790415763, 100000);
INSERT INTO Traffic_Controller VALUES(324, 44913, 12, 'Dallas Fort Worth 3', 9790425763, 100000);
CREATE TABLE Communicate(Comm_Flight_id INT, Comm_TC_id INT, Duration INT, FOREIGN KEY (Comm_Flight_id) REFERENCES Flight(Flight_id), FOREIGN KEY (Comm_TC_id) REFERENCES Traffic_Controller(TC_id));
INSERT INTO Communicate VALUES(20, 30, 5);
CREATE TABLE FAA(Max_Score INT, FAA_date date, Score INT, FAA_Name varchar(100), No_of_Hours time, Test_Number INT UNIQUE NOT NULL, FAA_Flight_id INT, FOREIGN KEY (FAA_Flight_id) REFERENCES Flight);
INSERT INTO FAA VALUES(71,'10/14/2018',67,'Alonzo Culpepper',10,123,33);
INSERT INTO FAA VALUES(82,'10/22/22',81,'Aman Barry Crouch',12,14,43);
INSERT INTO FAA VALUES(96,'12/11/69',69,'Hailey Johnna Wilson',13,129,239);
CREATE TABLE Staff_Member(Mem_Union_number INT PRIMARY KEY NOT NULL, Union_name varchar(100));
INSERT INTO Staff_Member VALUES(132455, 'AIRM');
CREATE TABLE Staff_Type(U_Ssn INT PRIMARY KEY NOT NULL, Mem_Union_number INT, Type varchar(100), FOREIGN KEY (Mem_Union_number) REFERENCES Staff_Member(Mem_Union_number));
INSERT INTO Staff_Type VALUES(332211223,10,'Tech');
CREATE TABLE Announcement_Notify(Time time, Notification varchar(1000));
INSERT INTO Announcement_Notify VALUES('10:00:00','Good afternoon passengers. This is the pre-boarding announcement for flight 89B to Rome. We are now inviting those passengers with small children, and any passengers requiring special assistance, to begin boarding at this time. Please have your boarding pass and identification ready. Regular boarding will begin in approximately ten minutes time. Thank you.');
CREATE TABLE Flight_weight_info(Company_name varchar(100) PRIMARY KEY NOT NULL, weight INT);
INSERT INTO Flight_weight_info VALUES('United Airlines', 1000);
CREATE TABLE Flight_capacity_info(Flight_id INT PRIMARY KEY NOT NULL, Company_name varchar(1000), Capacity INT, FOREIGN KEY (Company_name) REFERENCES Flight_weight_info(Company_name));
INSERT INTO Flight_capacity_info VALUES(124,'Americal Airlines',186);
CREATE TABLE Technician_Salary(Tech_ssn INT PRIMARY KEY NOT NULL, Salary INT);
INSERT INTO Technician_Salary VALUES(123456, 100000);
CREATE TABLE Technician_Address(Tech_ssn INT PRIMARY KEY NOT NULL, Mem_Union_number INT, Address varchar(1000), Phone_no INT, FOREIGN KEY (Mem_Union_number) REFERENCES Staff_Member(Mem_Union_number));
INSERT INTO Technician_Address VALUES(123456, 132455, 'Dallas Fort Worth', 8495533422);
CREATE TABLE Communicate_Duration(Comm_Flight_id INT PRIMARY KEY NOT NULL, Duration time);
INSERT INTO Communicate_Duration VALUES(10,'10:00:00');
CREATE TABLE Communicate_TC(Comm_Flight_id INT PRIMARY KEY NOT NULL, Comm_TC_id INT UNIQUE NOT NULL);
INSERT INTO Communicate_TC VALUES(10,124);
CREATE TABLE Technician (Tech_SSN INT PRIMARY KEY NOT NULL, Mem_Union_Number INT, Salary INT);
INSERT INTO Technician VALUES(123456, 132455, 100000);